import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const nunito_Sans = localFont({
  src: './fonts/Nunito_Sans/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf',
  variable: '--font-nunito-sans-font',
});
const roboto = localFont({
  src: './fonts/Roboto/Roboto-VariableFont_wdth,wght.ttf',
  variable: '--font-roboto-font',
});
const sofia = localFont({
  src: './fonts/Sofia/Sofia-Regular.ttf',
  variable: '--font-sofia-font',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ViktorDeitsura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nunito_Sans.variable} ${roboto.variable} ${sofia.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
